//zscript/smoke.zsc

Class FuelSmoke : Actor
{
	Default
	{
		Radius 128;
		Height 16;
		-SOLID;
		+NOCLIP;
		+INVISIBLE;
	}
	
	States
	{
		Spawn:
			SMOK A 1
			{
				if (random(0, 1) == 0)
				{
					A_SpawnParticleEX("White", TexMan.CheckForTexture("SMOKA0"), STYLE_None, SPF_FULLBRIGHT | SPF_ROLL, 450, 0, random(0, 359), random(-1024, 1024), random(-1024, 1024), -16, 0, 0, 4, 0.04, 0.02, 0.1, 0.5, -1, 2, random(0, 359), frandom(-1, 1));
				}
			}
			Loop;
	}
}